repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1  # Use the latest stable version
    hooks:
      - id: terraform_fmt              # Format Terraform code
      # - id: terraform_tflint           # Run TFLint for additional linting
      # - id: terraform_tfsec            # Run tfsec for security checks
      - id: terraform_docs             # Update terraform-docs automatically
        args:
          - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
          - --hook-config=--use-standard-markers=true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace        # Ensure no trailing whitespace
      - id: end-of-file-fixer          # Ensure file ends with a newline
      - id: check-merge-conflict       # Prevent merge conflicts in code
