name: OpenTofu Plan

on:
  pull_request:
    branches:
      - main

jobs:
  opentofu-plan:
    name: OpenTofu Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup OpenTofu
        run: |
          curl -L https://github.com/opentofu/opentofu/releases/latest/download/opentofu-linux-amd64 -o /usr/local/bin/opentofu
          chmod +x /usr/local/bin/opentofu

      - name: Initialize OpenTofu
        run: tofu init

      - name: OpenTofu Plan
        run: tofu plan
